---
- name: set up my machine
  hosts: localhost
  connection: local
  tasks:
    - name: install packages
      community.general.homebrew:
        update_homebrew: true
        upgrade_all: true
        name:
          - ansible
          - awscli
          - bash
          - cmake
          - duckdb
          - eza
          - genact
          - gnu-tar
          - grep
          - gh
          - jq
          - moreutils
          - mise
          - maccy
          - ngrok
          - peco
          - postgresql@16
          - tmux
          - tig
          - zsh-autosuggestions
          - zsh-completions
          - zsh-syntax-highlighting
          - vlc
          - logseq
          - superwhisper
          - ffmpeg
          - pkgconf
          - visual-studio-code

    - name: check pg_bigm.so
      stat:
        path: /opt/homebrew/opt/postgresql@16/lib/postgresql/pg_bigm.so
      register: rc_pg_bigm

    - name: install pg_bigm
      when: not rc_pg_bigm.stat.exists
      block:
        - name: prepare temporary directory for pg_bigm build
          ansible.builtin.tempfile:
            state: directory
          register: rc_tempdir

        - name: unarchive pg_bigm
          ansible.builtin.unarchive:
            src: "https://github.com/pgbigm/pg_bigm/archive/refs/tags/v1.2-20240606.tar.gz"
            dest: "{{ rc_tempdir.path }}"
            remote_src: yes

        - name: build pg_bigm
          ansible.builtin.command:
            cmd: "make USE_PGXS=1 PG_CONFIG=/opt/homebrew/opt/postgresql@16/bin/pg_config"
            chdir: "{{ rc_tempdir.path }}/pg_bigm-1.2-20240606"

        - name: install pg_bigm
          ansible.builtin.command:
            cmd: "make USE_PGXS=1 PG_CONFIG=/opt/homebrew/opt/postgresql@16/bin/pg_config install"
            chdir: "{{ rc_tempdir.path }}/pg_bigm-1.2-20240606"

        - name: clean up tmeporary directory
          ansible.builtin.file:
            path: "{{ rc_tempdir.path }}"
            state: absent

    - name: start postgresql
      community.general.homebrew_services:
        name: postgresql@16
        state: "{{ 'present' if rc_pg_bigm.stat.exists else 'restarted' }}"

    - name: prepare git and mise config directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      loop:
        - ~/.config/mise
        - ~/.config/git

    - name: copy files
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop:
        - src: assets/mac/zshrc
          dest: ~/.zshrc
        - src: assets/mac/zprofile
          dest: ~/.zprofile
        - src: assets/tmux.conf
          dest: ~/.tmux.conf
        - src: assets/gitignore
          dest: ~/.config/git/ignore

    - name: copy mise config file
      ansible.builtin.copy:
        src: assets/mise.config.toml
        dest: ~/.config/mise/config.toml
      register: rc_copy_mise_config

    - name: install mise
      ansible.builtin.command:
        cmd: mise install
      when: rc_copy_mise_config.changed

    - name: Clean up downloads directory
      ansible.builtin.shell: 'rm -rf ~/Downloads/*'
