if type mise &>/dev/null; then
  eval "$(mise activate zsh)"
fi

PROMPT="
%n@%m:%d
%# "

alias l='eza --git --group-directories-first -l --time-style long-iso'

export HISTFILE=${HOME}/.zsh_history
export HISTSIZE=100000
export SAVEHIST=10000000
setopt hist_ignore_dups
setopt hist_ignore_space
setopt EXTENDED_HISTORY
setopt share_history
setopt hist_ignore_all_dups
setopt hist_ignore_space
setopt hist_verify
setopt hist_reduce_blanks  
setopt hist_save_no_dups
setopt hist_no_store
setopt hist_expand
setopt inc_append_history
bindkey "^R" history-incremental-search-backward
bindkey "^S" history-incremental-search-forward

function peco-select-history() {
  BUFFER=$(\history -n -r 1 | peco --query "$LBUFFER")
  CURSOR=$#BUFFER
  zle clear-screen
}
zle -N peco-select-history
bindkey '^r' peco-select-history

zstyle ':completion:*' menu select=2
